package app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adalberto
 */
public class contrib extends javax.swing.JFrame {

    /**
     * Creates new form persona
     */
    
    private static final String driver="com.mysql.jdbc.Driver";
    private static final String USERNAME="root";
    private static final String PASSWORD="mysqlpas";
    private static final String URL="jdbc:mysql://localhost:3306/delegacion_nith";
    
    PreparedStatement ps;
    ResultSet rs;
    
    //Clase para la conexion
    public static Connection getConection() throws SQLException
    {
            Connection con = null; 
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
                //JOptionPane.showMessageDialog(null, "Conexión exitosa");
            } catch (ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "Error de conexión: "+e);
            }
            return con;
             
    }
        
    
    private void limpiarCajas()
    {
        txtFolio.setText(null);
        txtObra.setText(null);
        txtAbril.setText(null);
        txtJulio.setText(null);
        txtAgosto.setText(null);
        txtSeptiembre.setText(null);
        txtFaena.setText(null);
        txtReuniones.setText(null);
        txtObservaciones.setText(null);
    }
    
    public contrib()  {
        //Esto es el constructor de la clase.
        initComponents();
        
        // Codigo que muestra info de usuarios con JTable
        Connection con = null;
        try{
            DefaultTableModel model = new DefaultTableModel();
            jTableContrib.setModel(model);
            PreparedStatement ps = null;
            ResultSet rs = null;
            con = getConection();
            
            String sql = "Select folio, obra, abril, julio, agosto, septiembre, faena, reuniones, total, observaciones FROM Contribuciones";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd .getColumnCount();
                for (int i = 1; i <= cantidadColumnas; i++) {
                model.addColumn(rsMd.getColumnName(i));
            }
            
                int[] anchos = {80, 80, 80, 80, 80, 80, 120, 120, 80, 200}; // Anchos de las columnas
            for (int x = 0; x < cantidadColumnas; x++) {
                jTableContrib.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                for(int i = 0; i< cantidadColumnas; i++)
                {
                    filas[i] = rs.getObject(i+1);
                }
                model.addRow(filas);
            }
            
        } catch (SQLException e){ 
            JOptionPane.showMessageDialog(null, ""+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFaena = new javax.swing.JTextField();
        txtJulio = new javax.swing.JTextField();
        txtAgosto = new javax.swing.JTextField();
        txtSeptiembre = new javax.swing.JTextField();
        txtAbril = new javax.swing.JTextField();
        btnGuarda = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnLimpia = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtObra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContrib = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtReuniones = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        txtNU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(47, 106, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Editar contribución");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Obra");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Abril");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Julio");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Agosto");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("Septiembre");

        txtSeptiembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeptiembreActionPerformed(evt);
            }
        });

        btnGuarda.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnGuarda.setText("Guarda");
        btnGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaActionPerformed(evt);
            }
        });

        btnModifica.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        btnElimina.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        btnLimpia.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnLimpia.setText("Limpiar campos");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Faena");

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTableContrib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Obra", "Abril", "Julio", "Agosto", "Septiembre", "Faena", "Reuniones", "Observaciones", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableContrib);

        jButton2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jButton2.setText("Actualizar tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel11.setText("Contribuciones ");

        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel10.setText("Reuniones");

        jLabel12.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel12.setText("Observaciones");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Nombre. de ciudado");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("Folio");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Noto Sans", 3, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Instrucciones:\n\n°El folio de la contribución debe ser el \nmismo que el usuario para poder\nubicarlo.\n°Para insertar una contribución se debe \ncolocar el nombre del usuario para\nque esta se corresponda a el.");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel14.setText("Volver a registro de usuarios");

        jButton4.setText("Vovler a usuarios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnGuarda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnElimina))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtObservaciones)
                                        .addComponent(txtFaena, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSeptiembre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAgosto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtJulio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAbril, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtObra, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtReuniones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNU)
                                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBuscar)
                                            .addComponent(btnLimpia)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel1)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(114, 114, 114)
                        .addComponent(jButton1)
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(btnLimpia))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAbril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJulio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAgosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeptiembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReuniones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuarda)
                            .addComponent(btnModifica)
                            .addComponent(btnElimina))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeptiembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeptiembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeptiembreActionPerformed
    
    public int obtenerIdUsuarioRegistrado(String nombreUsuario) {
    Connection con = null;
    int idUsuario = -1; // Valor predeterminado si no se encuentra el usuario

    try {
        con = getConection(); // Obtener la conexión a la base de datos
        
        // Consulta para obtener el ID del usuario por su nombre (suponiendo que se busca por nombre)
        String query = "SELECT id FROM usuarios WHERE nombre = ?";
        
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, nombreUsuario); // Asignar el nombre del usuario a buscar
        
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            idUsuario = rs.getInt("id"); // Obtener el ID del usuario de la consulta
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            // Puedes manejar el caso en el que no se encuentra el usuario aquí
        }
        
        con.close(); // Cerrar la conexión a la base de datos
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: "+e);
        // Manejo de excepciones en caso de error de base de datos
    }
    
    return idUsuario;
}
    
    private void btnGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaActionPerformed
        //Clase que guarda datos en CRUD
        Connection con = null;
        
        //Esta variable trae el nombre de usuario desde un método
        String nombreUsuario = txtNU.getText();
        
        /**Esta variable invoca el metodo de obtener id de usuario, y pasa el parametro
        **/
        int idUsuario = obtenerIdUsuarioRegistrado(nombreUsuario);
        try {
            con = getConection();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Contribuciones (folio, obra, abril, julio, agosto, septiembre, faena, reuniones, observaciones) VALUES (?,?,?,?,?,?,?,?,?)");

        ps.setString(1, txtFolio.getText());
        ps.setInt(2, Integer.parseInt (txtObra.getText()));
        ps.setInt(3, Integer.parseInt (txtAbril.getText()));
        ps.setInt(4, Integer.parseInt (txtJulio.getText()));
        ps.setInt(5, Integer.parseInt (txtAgosto.getText()));
        ps.setInt(6, Integer.parseInt (txtSeptiembre.getText()));
        ps.setInt(7, Integer.parseInt (txtFaena.getText()));
        ps.setInt(8, Integer.parseInt (txtReuniones.getText()));
        ps.setString(9, txtObservaciones.getText());

        int resContrib = ps.executeUpdate();

        if (resContrib > 0) {
            JOptionPane.showMessageDialog(null, "Datos de ciudadano guardados");
            Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT LAST_INSERT_ID() AS last_id");
                int idContribucion = -1;
        
        if (rs.next()) {
            idContribucion = rs.getInt("last_id");

            // Insertar la asociación en la tabla 'inteUC' con el ID autoincrementable de la contribución
            PreparedStatement psInteUC = con.prepareStatement("INSERT INTO inteUC (idUsuario, idContribucion) VALUES (?,?)");
            psInteUC.setInt(1, idUsuario);
            psInteUC.setInt(2, idContribucion);

            int resInteUC = psInteUC.executeUpdate();

            if (resInteUC > 0) {
                JOptionPane.showMessageDialog(null, "Relación inteUC guardada");
                limpiarCajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar relación inteUC");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al obtener el ID de la contribución");
        }
    } else {
            JOptionPane.showMessageDialog(null, "Error al guardar datos de ciudadano");
        }

        con.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error de trycatch"+ e);
        limpiarCajas();
    }
    }//GEN-LAST:event_btnGuardaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        //Código de botón que Modifica datos en CRUD
        Connection con = null;
        
        try{
            
         con = getConection();
         ps = con.prepareStatement("UPDATE Contribuciones SET folio=?, obra=?, abril=?, julio=?, agosto=?, septiembre=?, fanea=?, observaciones=? WHERE folio=?");
         ps.setString(1, txtFolio.getText());
         ps.setString(2, txtObra.getText());
         ps.setString(3, txtAbril.getText());
         ps.setString(4, txtJulio.getText());
         ps.setString(5, txtAgosto.getText());
         ps.setString(6, txtSeptiembre.getText());
         ps.setString(7, txtSeptiembre.getText());
         ps.setString(8, txtObservaciones.getText());
         
         int res= ps.executeUpdate();
         
         if(res>0){
             JOptionPane.showMessageDialog(null,"Datos de ciudadano modificada");
             limpiarCajas();
         }else
         {
             JOptionPane.showMessageDialog(null, "Error al modificar datos de ciudadano");
         }
             
        con.close();
         
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            limpiarCajas();
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        // Código de botón que limpia las cajas de registro en CRUD
        limpiarCajas();
    }//GEN-LAST:event_btnLimpiaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Código de botón que busca datos en CRUD
        Connection con = null;
        
        try{
            
         con = getConection();
         ps = con.prepareStatement("SELECT * FROM Contribuciones WHERE folio = ?" );
         ps.setString(1, txtFolio.getText());
         rs = ps.executeQuery();
         
         if(rs.next()){
            txtFolio.setText(rs.getString("folio"));
            txtObra.setText(rs.getString("obra"));
            txtAbril.setText(rs.getString("abril"));
            txtJulio.setText(rs.getString("julio"));
            txtAgosto.setText(rs.getString("agosto"));
            txtSeptiembre.setText(rs.getString("septiembre"));         
            txtFaena.setText(rs.getString("faena"));
            txtReuniones.setText(rs.getString("reuniones"));
            txtObservaciones.setText(rs.getString("observaciones"));
            
         }else
         {
             JOptionPane.showMessageDialog(null, "No existe una persona con la clave");
         }
             
        con.close();
         
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            limpiarCajas();
        }
        
         
         
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        //Código de botón que elimina datos en CRUD
        Connection con = null;
        
        try{
            
         con = getConection();
         ps = con.prepareStatement("DELETE FROM Contribucion WHERE folio=?");
         ps.setInt(1, Integer.parseInt(txtFolio.getText()));
         
         
         int res= ps.executeUpdate();
         
         if(res>0){
             JOptionPane.showMessageDialog(null,"Datos de ciudadano eliminados");
             limpiarCajas();
         }else
         {
             JOptionPane.showMessageDialog(null, "Error al eliminar datos de ciudadano");
             limpiarCajas();
         }
             
        con.close();
         
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            limpiarCajas();
        }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            //Boton que regresa a clase Inicio
            this.dispose();
            inicio inicio = new inicio();
            inicio.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        contrib contrib = new contrib();
        contrib.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        persona persona = new persona();
        persona.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contrib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contrib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contrib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contrib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new contrib().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnGuarda;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableContrib;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtAbril;
    private javax.swing.JTextField txtAgosto;
    private javax.swing.JTextField txtFaena;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtJulio;
    private javax.swing.JTextField txtNU;
    private javax.swing.JTextField txtObra;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtReuniones;
    private javax.swing.JTextField txtSeptiembre;
    // End of variables declaration//GEN-END:variables

    private Connection getConnection() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
